# Generated by Django 5.2.3 on 2025-07-01 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=40)),
                ('asset_type', models.CharField(blank=True, max_length=40, null=True)),
                ('ipo_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delisting_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api_rest.ticker')),
            ],
        ),
    ]
