# Generated by Django 5.2.3 on 2025-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
